models:
  - name: clients
    description: "A model to get the latest client information from the clients raw source table."
    columns:
      - name: client_id
        description: "Unique identifier for the client."
        tests:
          - not_null
          - unique
      - name: client_name
        description: "Name of the client."
        tests:
          - not_null
      - name: client_email
        description: "Email address of the client."
        tests:
          - not_null
          - unique

  - name: cars
    description: "A model to get the latest cars information from the car raw source table."
    columns:
      - name: product_id
        description: "Unique identifier for the car."
        tests:
          - not_null
          - unique
      - name: brand
        description: "Name of the car manufacturer."
        tests:
          - not_null
          - accepted_values:
              values: ['Peugeot', 'Toyota', 'Ford', 'Honda', 'Nissan', 'Chevrolet', 'Volkswagen']
      - name: model
        description: "Model name of the car."
        tests:
          - not_null
      - name: price
        description: "Market price."
        tests:
          - not_null

  - name: transactions
    description: "Latest transaction information from the transactions source table."
    columns:
      - name: transaction_id
        description: "Unique identifier for the transaction."
        tests:
          - not_null
          - unique
      - name: product_id
        description: "Unique identifier for the product."
        tests:
          - not_null
          - relationships:
              to: ref('cars')
              field: product_id
      - name: client_id
        description: "Unique identifier for the client."
        tests:
          - not_null
          - relationships:
              to: ref('clients')
              field: client_id
      - name: product_quantity_sold
        description: "The quantity of the product sold."
        tests:
          - not_null
      - name: turnover
        description: "Total turnover generated by the sale of the product."
        tests:
          - not_null
      - name: transaction_time
        description: "Timestamp of the transaction."
        tests:
          - not_null
      - name: transaction_datetime
        description: "Transaction time adjusted to CET."
        tests:
          - not_null
